# Generated by Django 4.2.3 on 2024-10-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Herramienta',
            new_name='Potencialidad',
        ),
    ]
