# Generated by Django 4.2.16 on 2024-10-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_conversacion_alter_servicio_imagen_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen_dir',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='clase',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fuente',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
