# Generated by Django 4.2.16 on 2024-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_equipo_imagen_dir_equipo_link_link_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen_dir',
            field=models.CharField(default='imagenes/equipo/<django.db.models.fields.CharField>.jpg', max_length=255),
        ),
    ]
