# Generated by Django 4.2.16 on 2024-10-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_equipo_imagen_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='apellido',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cargo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='imagen_dir',
            field=models.CharField(default='imagenes/equipo/nombre.jpg', max_length=255),
        ),
    ]
