# Generated by Django 4.2.16 on 2024-10-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_equipo_apellido_alter_equipo_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fuente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='clase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
