# Generated by Django 4.2.16 on 2024-10-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_parrafo_sobrenosotros_parrafo1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobrenosotros',
            old_name='parrafo1',
            new_name='parrafo',
        ),
    ]
