# Generated by Django 4.2.16 on 2024-10-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_sobrenosotros_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrenosotros',
            name='documento',
            field=models.FileField(upload_to='documentos'),
        ),
    ]
