# Generated by Django 4.2.3 on 2024-10-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_sobrenosotros_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrenosotros',
            name='documento_dir',
            field=models.FileField(default='/media/documentos/datos.doc', upload_to='documentos'),
        ),
    ]
