# Generated by Django 4.2.3 on 2024-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_sobrenosotros_documento_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='clase',
            field=models.CharField(default='fas fa-cloud', max_length=255),
        ),
    ]
