# Generated by Django 4.2.3 on 2024-10-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_categoria_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen_dir',
            field=models.CharField(default='media/imagenes/servicios/nombre.jpg', max_length=255),
        ),
    ]
