# Generated by Django 4.2.3 on 2024-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_servicio_imagen_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen_dir',
            field=models.CharField(default='/media/imagenes/equipo/nombre.jpg', max_length=255),
        ),
    ]
