# Generated by Django 4.2.3 on 2024-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
