# Generated by Django 4.2.3 on 2024-10-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_catalogo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='action',
            field=models.ImageField(upload_to='imagenes/index'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='skills',
            field=models.ImageField(upload_to='imagenes/index'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='why_us',
            field=models.ImageField(upload_to='imagenes/index'),
        ),
    ]
