# Generated by Django 5.1.1 on 2024-10-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_catalogo_action_alter_catalogo_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='action_dir',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='hero_dir',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='skills_dir',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='why_us_dir',
        ),
    ]
