# Generated by Django 5.1.1 on 2024-10-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_catalogo_action_dir_remove_catalogo_hero_dir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='imagen_dir',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen_dir',
        ),
        migrations.RemoveField(
            model_name='sobrenosotros',
            name='documento_dir',
        ),
    ]
