# Generated by Django 5.1.1 on 2024-10-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_equipo_imagen_dir_remove_servicio_imagen_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/index'),
        ),
    ]
