# Generated by Django 5.1.1 on 2024-10-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_comentario_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/servicios'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/servicios'),
        ),
    ]
