# Generated by Django 5.1.1 on 2024-10-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_servicio_imagen2_servicio_imagen3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.servicio'),
            preserve_default=False,
        ),
    ]
