# Generated by Django 5.1.1 on 2024-10-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_catalogo_fondo_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='enviado_por',
            field=models.CharField(choices=[('assistant', 'Asistente'), ('user', 'Usuario')], max_length=255),
        ),
    ]
