# Generated by Django 5.1.1 on 2024-10-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_mensaje_enviado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacion',
            name='fecha_fin',
        ),
    ]
