# Generated by Django 5.1.1 on 2024-10-12 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_conversacion_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_prompt', models.TextField()),
                ('energux_prompt', models.TextField()),
                ('myros_prompt', models.TextField()),
                ('servidores_prompt', models.TextField()),
                ('fastos_pagus_prompt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('resumen', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicio', verbose_name='Servicio')),
            ],
        ),
    ]
