# Generated by Django 5.1.1 on 2024-10-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_chatbot_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='nombre',
            field=models.CharField(default='ChatBot', max_length=255),
        ),
    ]
