# Generated by Django 5.1.1 on 2024-10-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_chatbot_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
