# Generated by Django 5.1.1 on 2024-10-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_chatbot_activo_solicitud_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='enviado_por',
            field=models.CharField(choices=[('assistant', 'Asistente'), ('user', 'Usuario'), ('system', 'Sistema')], max_length=255),
        ),
    ]
