# Generated by Django 5.1.1 on 2024-10-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_chatbot_x_alter_chatbot_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='facebook',
            field=models.CharField(default='<a href="https://www.facebook.com/SolucionesDTeam" class="facebook">Facebook <i class="bx bxl-facebook"></i></a>', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='instagram',
            field=models.CharField(default='<a href="https://www.instagram.com/solucionesdteam/" class="instagram">Instagram <i class="bx bxl-instagram"></i></a>', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='telegram',
            field=models.CharField(default='<a href="https://t.me/clientesDesoftSSP" class="telegram">Telegram <i class="bx bxl-telegram"></i></a>', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='whatsapp',
            field=models.CharField(default='<a href="https://chat.whatsapp.com/GXwpDNRWs1F6NOM1Z2fzbc">Whatsapp <i class="bx bxl-whatsapp"></i></a></a>', max_length=255),
        ),
    ]
