# Generated by Django 5.1.1 on 2024-10-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_generales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='resumen',
            new_name='datos',
        ),
    ]
