# Generated by Django 5.1.1 on 2024-10-14 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_rename_resumen_solicitud_datos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente Potencial')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicio', verbose_name='Servicio')),
            ],
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
