# Generated by Django 5.1.1 on 2024-10-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_solicitud_cuestionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='X',
            field=models.CharField(default='<a href="https://x.com/DesoftSsp" class="twitter">X <i class="bx bxl-twitter" target="_blank"></i></a>', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='facebook',
            field=models.CharField(default='<a href="https://www.facebook.com/SolucionesDTeam" class="facebook" target="_blank">Facebook <i class="bx bxl-facebook"></i></a>', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='instagram',
            field=models.CharField(default='<a href="https://www.instagram.com/solucionesdteam/" class="instagram" target="_blank">Instagram <i class="bx bxl-instagram"></i></a>', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='telegram',
            field=models.CharField(default='<a href="https://t.me/clientesDesoftSSP" class="telegram" target="_blank">Telegram <i class="bx bxl-telegram"></i></a>', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='whatsapp',
            field=models.CharField(default='<a href="https://chat.whatsapp.com/GXwpDNRWs1F6NOM1Z2fzbc" target="_blank">Whatsapp <i class="bx bxl-whatsapp"></i></a></a>', max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('declined', 'Rechazado')], default='pending', max_length=255),
        ),
    ]
