# Generated by Django 5.1.1 on 2024-10-20 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_chatbot_x_alter_chatbot_facebook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_pot',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='empresa',
        ),
        migrations.AddField(
            model_name='cliente_pot',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='generales',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.generales'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente_pot',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicio'),
        ),
    ]
