# Generated by Django 5.1.1 on 2024-10-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_cliente_pot_cliente_remove_solicitud_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='generales_prompt',
            field=models.TextField(default='Almacena las generales de una empresa y las asocia al usuario para poder crear solicitudes de contratos.'),
        ),
    ]
