# Generated by Django 5.1.1 on 2024-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='voto_valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
