# Generated by Django 5.1.1 on 2024-10-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_opinion_voto_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='voto_valor',
            new_name='puntuacion',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='voto',
        ),
    ]
