# Generated by Django 5.1.1 on 2024-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_rename_voto_valor_opinion_puntuacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='fondo_login_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/login'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='fondo_login_pc',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/login'),
        ),
    ]
