# Generated by Django 5.1.1 on 2024-10-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_correos'),
    ]

    operations = [
        migrations.AddField(
            model_name='correos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
