# Generated by Django 5.1.1 on 2024-11-02 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_puntuacion_delete_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntuacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.servicio'),
        ),
    ]
