# Generated by Django 5.1.2 on 2024-11-03 13:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_puntuacion_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='energux_prompt',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='fastos_pagus_prompt',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='myros_prompt',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='servidores_prompt',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='sys_prompt',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='potencialidad',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='respuesta',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='parrafo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cuestionario',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='observaciones',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
