# Generated by Django 5.1.2 on 2024-11-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='energux_prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='fastos_pagus_prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='myros_prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='servidores_prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='sys_prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='potencialidad',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='respuesta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='parrafo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cuestionario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='observaciones',
            field=models.TextField(),
        ),
    ]
